CREATE TABLE aie_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password TEXT NOT NULL,
  admin BOOLEAN,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE aie_articles
  ADD COLUMN
    author_id INTEGER REFERENCES aie_users(id)
    ON DELETE SET NULL;
